import { env } from "@/env.mjs";
import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl:
    env.NODE_ENV === "development"
      ? "http://localhost:3000/api"
      : "https://dynbox.co/api",
});
export const api = createClient(fetchClient);
