import { cn } from "@/lib/css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TitleBar from "./_components/title-bar";
import "./globals.css";
import Providers from './providers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          "bg-background animate-in fade-in text-foreground flex h-full flex-col overflow-hidden antialiased duration-1000",
          geistSans.variable,
          geistMono.variable,
        )}
      >
        <Providers>
          <TitleBar />
          <main className="h-full w-full overflow-hidden">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
